services:

  'yozh\SandboxBundle\Service\SanboxPublicService':
    class: yozh\SandboxBundle\Service\SanboxPublicService
    public: true
    autowire: true

  'yozh\SandboxBundle\Service\SanboxPrivateService':
    class: yozh\SandboxBundle\Service\SanboxPrivateService
    public: false
    arguments:
      - '@logger'
